#!/usr/bin/env python3
"""Regenerate tests/fixtures/hermes-cron-list.txt from the real Hermes CLI.

WHY THIS EXISTS
===============
The cron parser in `scripts/deck-collect` was written against a wrong output
format THREE times, and each time the tests passed because the fixture had been
typed by hand to match whatever the parser already expected. A hand-written
fixture cannot falsify a wrong assumption about an external system — it just
records the assumption.

So the fixture is generated by calling the CLI's own rendering functions, and
this script is the provenance. If `parse_cron_list` is ever suspected of
drifting, re-run this and diff.

USAGE
    python3 tests/fixtures/generate-cron-fixture.py            # write the file
    python3 tests/fixtures/generate-cron-fixture.py --check    # fail if stale

It needs the Hermes source tree (default `~/.hermes/hermes-agent`, override with
`--hermes-src`). It is NOT run in CI: no Hermes install exists there, so the
generated fixture is committed and this script only has to run on a developer
machine when the CLI's output format changes.

The two synthetic jobs are chosen to cover the branches the parser must get
right: an enabled job (badge `[active]`) and a disabled/paused one (badge
`[paused]`, which only appears at all when `--all` is passed).
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import shutil
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
TARGET = HERE / "hermes-cron-list.txt"

# Deliberately plain job dicts. They are NOT a fixture of the CLI's output — they
# are inputs to the CLI's own formatter, which produces the output.
JOBS = [
    {
        # A hex id — the common case.
        "id": "182cc80c63f6",
        "name": "nightly-backup",
        "schedule_display": "0 3 * * *",
        "schedule": {"value": "0 3 * * *"},
        "enabled": True,
        "state": "scheduled",
        "next_run_at": "2026-09-23T03:00:00",
        "repeat": {},
        "deliver": ["local"],
        "prompt": "back up the vault",
        "last_status": "ok",
        "last_run_at": "2026-09-22T03:00:00",
    },
    {
        # enabled=False -> only visible with --all, badge [paused].
        "id": "aabbccddeeff",
        "name": "weekly-digest",
        "schedule_display": "0 9 * * 1",
        "schedule": {"value": "0 9 * * 1"},
        "enabled": False,
        "state": "paused",
        "paused_at": "2026-09-20T00:00:00",
        "next_run_at": "-",
        "repeat": {},
        "deliver": ["local"],
        "prompt": "summarize the week",
    },
    {
        # A NON-HEX id. `_normalize_job_record` uses an ID-keyed map's key
        # verbatim (cron/jobs.py:1339), so this is a legal real id — and a
        # parser that assumed hex ids silently dropped the job. Covering it here
        # is the point: the previous JOBS list hardcoded hex ids, so the fixture
        # encoded the hex assumption instead of falsifying it.
        "id": "my-backup_2",
        "name": "external-tool-job",
        "schedule_display": "@daily",
        "schedule": {"value": "@daily"},
        "enabled": True,
        "state": "scheduled",
        "next_run_at": "2026-09-23T00:00:00",
        "repeat": {},
        "deliver": ["local"],
        "prompt": "arrived from an external tool",
    },
    {
        # A missing/null id, which the producer coerces to the literal "unknown"
        # (cron/jobs.py:495). Also not hex.
        "id": None,
        "name": "hand-edited-record",
        "schedule_display": "30 4 * * *",
        "schedule": {"value": "30 4 * * *"},
        "enabled": True,
        "state": "scheduled",
        "next_run_at": "2026-09-23T04:30:00",
        "repeat": {},
        "deliver": ["local"],
        "prompt": "legacy record with no id",
    },
    {
        # A job whose whole name is a bracketed token: the field row
        # `    Name:      [urgent]` must never be read as a job header.
        "id": "99887766aabb",
        "name": "[urgent]",
        "schedule_display": "*/5 * * * *",
        "schedule": {"value": "*/5 * * * *"},
        "enabled": True,
        "state": "scheduled",
        "next_run_at": "2026-09-22T15:05:00",
        "repeat": {},
        "deliver": ["local"],
        "prompt": "bracket-named job",
    },
    {
        # A job with NO name whose prompt is MULTI-LINE. `_normalize_job_record`
        # derives the display name from the prompt when no name is set
        # (cron/jobs.py:497-507, `label_source[:50]`), newlines included. The CLI
        # then prints the prompt's continuation lines VERBATIM inside the Name
        # field, so a prompt containing an indented `[badge]` line renders what
        # looks exactly like a job header:
        #
        #     aaa111 [active]
        #       Name:      ok
        #     injected [paused]        <- not a job; the prompt's second line
        #       Name: evil             <- not a job's name
        #       Schedule:  0 3 * * *   <- belongs to aaa111
        #
        # The previous parser flushed on that fake header and reported a
        # FABRICATED job ("evil", paused, schedule 0 3 * * *) while dropping the
        # real one. Reachable with zero hand-editing: any unnamed job whose prompt
        # contains an indented line in the badge vocabulary does it.
        "id": "aaa111bbb222",
        # The continuation line carries exactly the header indent (two spaces),
        # which is what makes it hostile. A flush guard that requires the new
        # fragment to have a name AND a schedule cannot save this: the injected
        # block brings BOTH (the fake Name line, then the real job's Schedule).
        "prompt": "ok\n  injected [paused]\n    Name: evil\n    Schedule: 0 0 * * *",
        "schedule_display": "0 3 * * *",
        "schedule": {"value": "0 3 * * *"},
        "enabled": True,
        "state": "scheduled",
        "next_run_at": "2026-09-23T03:00:00",
        "repeat": {},
        "deliver": ["local"],
    },
]


def render(hermes_src: Path, show_all: bool) -> str:
    """Render `hermes cron list` by CALLING it, in a throwaway store.

    This function used to reimplement cron_list's loop — calling its helpers
    `_print_banner`/`_job_rows` but iterating the jobs itself. That skipped
    `cron.jobs.list_jobs` -> `_normalize_job_record`, which is where a null id is
    coerced to the literal "unknown" (cron/jobs.py:495). The result was a fixture
    containing `  None [active]` where the real CLI prints `  unknown [active]`,
    and a `--check` gate that compared the fixture against the same
    reimplementation — so it reported "matches the CLI" while the fixture did not
    match. A provenance check that never executes the real code cannot detect
    drift, which is the only thing it exists for.

    So: write a real jobs.json into a temporary HERMES_HOME, point the cron store
    at it, and call `cron_list` itself. Then the fixture IS the CLI's output.
    """
    import os

    sys.path.insert(0, str(hermes_src))
    import hermes_cli.cron as cron_cli  # noqa: PLC0415
    from cron import jobs as cron_jobs  # noqa: PLC0415

    tmp = tempfile.mkdtemp(prefix="cron-fixture-")
    cron_dir = Path(tmp) / "cron"
    cron_dir.mkdir(parents=True, exist_ok=True)
    (cron_dir / "jobs.json").write_text(
        json.dumps({"jobs": [dict(job) for job in JOBS]}), encoding="utf-8"
    )

    # Redirect the store with upstream's own contextmanager, not by mutating five
    # module globals by hand. `use_cron_store` (cron/jobs.py:171) sets a
    # ContextVar and restores it on exit, so there is no window where the real
    # store is unreachable and no `finally` that can forget one of the fields —
    # hand-rolled global mutation is how a leaked temp dir went unnoticed.
    buf = io.StringIO()
    with cron_jobs.use_cron_store(tmp):
        # No ANSI: color is suppressed when stdout is not a tty, which is the
        # case here because we redirect it.
        with contextlib.redirect_stdout(buf):
            cron_cli.cron_list(show_all=show_all)
    # Remove the throwaway store. Every invocation (including every --check in the
    # gate) used to leave a /tmp/cron-fixture-* directory behind holding a real
    # jobs.json — 44 had accumulated.
    shutil.rmtree(tmp, ignore_errors=True)
    return buf.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hermes-src", default=str(Path.home() / ".hermes" / "hermes-agent"))
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the committed fixture differs")
    parser.add_argument("--show-bare", action="store_true",
                        help="also print what bare `cron list` (no --all) emits")
    args = parser.parse_args()

    src = Path(args.hermes_src)
    if not (src / "hermes_cli" / "cron.py").is_file():
        print(f"generate-cron-fixture: no Hermes source at {src} "
              "(pass --hermes-src)", file=sys.stderr)
        return 2

    rendered = render(src, show_all=True)
    if args.show_bare:
        bare = render(src, show_all=False)
        print("--- bare `cron list` (no --all) ---", file=sys.stderr)
        print(bare, file=sys.stderr)
        print("--- with --all (what the collector runs) ---", file=sys.stderr)

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if current != rendered:
            print("generate-cron-fixture: the committed fixture is STALE — "
                  "regenerate it and re-run the suite", file=sys.stderr)
            return 1
        print("fixture matches the CLI's current output")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(TARGET.parents[2])} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
