#!/usr/bin/env python3
"""Regenerate tests/fixtures/hermes-cron-list.txt from the real Hermes CLI.

WHY THIS EXISTS
===============
The cron parser in `scripts/deck-collect` was written against a wrong output
format THREE times, and each time the tests passed because the fixture had been
typed by hand to match whatever the parser already expected. A hand-written
fixture cannot falsify a wrong assumption about an external system — it just
records the assumption.

So the fixture is generated by calling the CLI's own rendering functions, and
this script is the provenance. If `parse_cron_list` is ever suspected of
drifting, re-run this and diff.

USAGE
    python3 tests/fixtures/generate-cron-fixture.py            # write the file
    python3 tests/fixtures/generate-cron-fixture.py --check    # fail if stale

It needs the Hermes source tree (default `~/.hermes/hermes-agent`, override with
`--hermes-src`). It is NOT run in CI: no Hermes install exists there, so the
generated fixture is committed and this script only has to run on a developer
machine when the CLI's output format changes.

The two synthetic jobs are chosen to cover the branches the parser must get
right: an enabled job (badge `[active]`) and a disabled/paused one (badge
`[paused]`, which only appears at all when `--all` is passed).
"""

from __future__ import annotations

import argparse
import contextlib
import io
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TARGET = HERE / "hermes-cron-list.txt"

# Deliberately plain job dicts. They are NOT a fixture of the CLI's output — they
# are inputs to the CLI's own formatter, which produces the output.
JOBS = [
    {
        "id": "182cc80c63f6",
        "name": "nightly-backup",
        "schedule_display": "0 3 * * *",
        "schedule": {"value": "0 3 * * *"},
        "enabled": True,
        "state": "scheduled",
        "next_run_at": "2026-09-23T03:00:00",
        "repeat": {},
        "deliver": ["local"],
        "prompt": "back up the vault",
        "last_status": "ok",
        "last_run_at": "2026-09-22T03:00:00",
    },
    {
        "id": "aabbccddeeff",
        "name": "weekly-digest",
        "schedule_display": "0 9 * * 1",
        "schedule": {"value": "0 9 * * 1"},
        "enabled": False,
        "state": "paused",
        "paused_at": "2026-09-20T00:00:00",
        "next_run_at": "-",
        "repeat": {},
        "deliver": ["local"],
        "prompt": "summarize the week",
    },
]


def render(hermes_src: Path, show_all: bool) -> str:
    """Render `hermes cron list` output by calling the CLI's own functions."""
    sys.path.insert(0, str(hermes_src))
    import hermes_cli.cron as cron_cli  # noqa: PLC0415
    from cron.jobs import effective_job_state  # noqa: PLC0415

    # `list_jobs(include_disabled=False)` drops enabled=False records, which is
    # exactly what bare `hermes cron list` does — reproduce it so the difference
    # between the two modes is visible rather than assumed.
    jobs = [j for j in JOBS if j.get("enabled", True) or show_all]

    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        cron_cli._print_banner("Scheduled Jobs")
        for job in jobs:
            badge = cron_cli._STATE_BADGES.get(effective_job_state(job)) or (
                ("[active]", None) if job.get("enabled", True) else ("[disabled]", None)
            )
            print(f"  {job.get('id', '?')} {badge[0]}")
            for label, value in cron_cli._job_rows(job):
                print(f"    {label + ':':<11}{value}")
            print()
    return buf.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hermes-src", default=str(Path.home() / ".hermes" / "hermes-agent"))
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the committed fixture differs")
    parser.add_argument("--show-bare", action="store_true",
                        help="also print what bare `cron list` (no --all) emits")
    args = parser.parse_args()

    src = Path(args.hermes_src)
    if not (src / "hermes_cli" / "cron.py").is_file():
        print(f"generate-cron-fixture: no Hermes source at {src} "
              "(pass --hermes-src)", file=sys.stderr)
        return 2

    rendered = render(src, show_all=True)
    if args.show_bare:
        bare = render(src, show_all=False)
        print("--- bare `cron list` (no --all) ---", file=sys.stderr)
        print(bare, file=sys.stderr)
        print("--- with --all (what the collector runs) ---", file=sys.stderr)

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if current != rendered:
            print("generate-cron-fixture: the committed fixture is STALE — "
                  "regenerate it and re-run the suite", file=sys.stderr)
            return 1
        print("fixture matches the CLI's current output")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(TARGET.parents[2])} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
